#!/bin/bash
# manage.sh — Multi-user CLAUDE.md Manager
#
# Installs role-specific CLAUDE.md configurations for team members.
# Combines a shared base policy with role-specific rules and records
# an audit trail of installations.
#
# Usage:
#   ./manage.sh install --role engineer   # install engineer config
#   ./manage.sh list                      # show current role and version
#   ./manage.sh verify                    # check if config is up to date
#   ./manage.sh audit                     # show installation history
#   ./manage.sh roles                     # list available roles
#
# Roles: engineer | analyst | manager

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIGS_DIR="$SCRIPT_DIR/configs"
CLAUDE_DIR="${HOME}/.claude"
TARGET="$CLAUDE_DIR/CLAUDE.md"
META_FILE="$CLAUDE_DIR/.config-meta.json"

VALID_ROLES="engineer analyst manager"

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ── Helpers ──────────────────────────────────────────────────────────────────

version_of() {
    local file="$1"
    # Extract version from header comment: # Version: 1.0.0
    grep -m1 '^# Version:' "$file" 2>/dev/null | awk '{print $3}' || echo "unversioned"
}

hash_of() {
    local file="$1"
    if command -v md5sum &>/dev/null; then
        md5sum "$file" | awk '{print $1}'
    else
        md5 -q "$file"
    fi
}

read_meta() {
    local key="$1"
    if [ -f "$META_FILE" ]; then
        python3 -c "
import json, sys
data = json.load(open('$META_FILE'))
history = data.get('history', [])
latest = history[-1] if history else {}
print(latest.get('$key', 'unknown'))
" 2>/dev/null || echo "unknown"
    else
        echo "not installed"
    fi
}

write_meta() {
    local role="$1"
    local version="$2"
    local hash="$3"
    local installed_by
    installed_by="$(git config user.name 2>/dev/null || echo "$USER")"

    python3 - <<PYEOF
import json, os
from datetime import datetime, timezone

meta_file = '$META_FILE'
data = {}
if os.path.exists(meta_file):
    try:
        data = json.load(open(meta_file))
    except Exception:
        data = {}

history = data.get('history', [])
history.append({
    'role': '$role',
    'version': '$version',
    'hash': '$hash',
    'installed_at': datetime.now(timezone.utc).isoformat(),
    'installed_by': '$installed_by'
})

data['history'] = history
data['current'] = history[-1]

with open(meta_file, 'w') as f:
    json.dump(data, f, indent=2)
PYEOF
}

# ── Commands ─────────────────────────────────────────────────────────────────

cmd_install() {
    local role=""
    local dry_run=false
    local force=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --role) role="$2"; shift 2 ;;
            --dry-run) dry_run=true; shift ;;
            --force) force=true; shift ;;
            *) echo "Unknown option: $1"; exit 1 ;;
        esac
    done

    if [ -z "$role" ]; then
        echo -e "${RED}Error: --role is required${NC}"
        echo "Usage: ./manage.sh install --role <engineer|analyst|manager>"
        exit 1
    fi

    if ! echo "$VALID_ROLES" | grep -qw "$role"; then
        echo -e "${RED}Error: unknown role '$role'${NC}"
        echo "Available roles: $VALID_ROLES"
        exit 1
    fi

    local base_file="$CONFIGS_DIR/base.md"
    local role_file="$CONFIGS_DIR/${role}.md"

    if [ ! -f "$base_file" ]; then
        echo -e "${RED}Error: base.md not found at $base_file${NC}"
        exit 1
    fi

    if [ ! -f "$role_file" ]; then
        echo -e "${RED}Error: role config not found at $role_file${NC}"
        exit 1
    fi

    local base_version; base_version=$(version_of "$base_file")
    local role_version; role_version=$(version_of "$role_file")
    local combined_version="${base_version}+${role_version}"

    # Check if already installed with same version
    if [ "$force" = false ] && [ -f "$TARGET" ]; then
        local current_role; current_role=$(read_meta "role")
        local current_version; current_version=$(read_meta "version")
        if [ "$current_role" = "$role" ] && [ "$current_version" = "$combined_version" ]; then
            echo -e "${YELLOW}Already up to date:${NC} role=$role version=$combined_version"
            echo "Use --force to reinstall."
            exit 0
        fi
    fi

    echo -e "${CYAN}Installing CLAUDE.md...${NC}"
    echo "  Role:    $role"
    echo "  Version: $combined_version"
    echo "  Target:  $TARGET"
    echo ""

    if [ "$dry_run" = true ]; then
        echo -e "${YELLOW}[DRY RUN] Would write:${NC}"
        echo "──────────────────────────────────"
        {
            echo "# CLAUDE.md — Role: ${role} | Version: ${combined_version}"
            echo "# Generated by claude-config-manager on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
            echo "# DO NOT EDIT MANUALLY — changes will be overwritten on next install"
            echo ""
            cat "$base_file"
            echo ""
            echo "---"
            echo ""
            cat "$role_file"
        } | head -30
        echo "... (truncated)"
        echo "──────────────────────────────────"
        echo -e "${YELLOW}[DRY RUN] No changes made.${NC}"
        exit 0
    fi

    # Backup existing
    if [ -f "$TARGET" ]; then
        local backup="${TARGET}.bak.$(date +%Y%m%d%H%M%S)"
        cp "$TARGET" "$backup"
        echo -e "  Backup:  $(basename "$backup")"
    fi

    # Combine base + role → target
    mkdir -p "$CLAUDE_DIR"
    {
        echo "# CLAUDE.md — Role: ${role} | Version: ${combined_version}"
        echo "# Generated by claude-config-manager on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
        echo "# DO NOT EDIT MANUALLY — run './manage.sh install --role ${role}' to update"
        echo ""
        cat "$base_file"
        echo ""
        echo "---"
        echo ""
        cat "$role_file"
    } > "$TARGET"

    local installed_hash; installed_hash=$(hash_of "$TARGET")
    write_meta "$role" "$combined_version" "$installed_hash"

    echo -e "${GREEN}✅ Installed successfully.${NC}"
    echo ""
    echo "Next steps:"
    echo "  Restart Claude Code to apply the new configuration."
    echo "  Run './manage.sh verify' to confirm the installation."
}

cmd_list() {
    echo -e "${BOLD}Current CLAUDE.md Configuration${NC}"
    echo "────────────────────────────────"

    if [ ! -f "$TARGET" ]; then
        echo -e "${YELLOW}Not installed.${NC} Run: ./manage.sh install --role <role>"
        exit 0
    fi

    local role; role=$(read_meta "role")
    local version; version=$(read_meta "version")
    local installed_at; installed_at=$(read_meta "installed_at")
    local installed_by; installed_by=$(read_meta "installed_by")

    printf "  %-20s %s\n" "Role:" "$role"
    printf "  %-20s %s\n" "Version:" "$version"
    printf "  %-20s %s\n" "Installed at:" "$installed_at"
    printf "  %-20s %s\n" "Installed by:" "$installed_by"
    printf "  %-20s %s\n" "Target:" "$TARGET"
}

cmd_verify() {
    echo -e "${BOLD}Verifying CLAUDE.md...${NC}"

    if [ ! -f "$TARGET" ]; then
        echo -e "${RED}❌ Not installed.${NC}"
        exit 1
    fi

    local current_hash; current_hash=$(hash_of "$TARGET")
    local stored_hash; stored_hash=$(read_meta "hash")

    if [ "$current_hash" = "$stored_hash" ]; then
        echo -e "${GREEN}✅ CLAUDE.md matches installed version.${NC}"
        local role; role=$(read_meta "role")
        local version; version=$(read_meta "version")
        echo "   Role: $role | Version: $version"
    else
        echo -e "${RED}❌ CLAUDE.md has been modified since installation.${NC}"
        echo "   Expected hash: $stored_hash"
        echo "   Current hash:  $current_hash"
        echo ""
        echo "   To restore: ./manage.sh install --role $(read_meta 'role') --force"
        exit 1
    fi
}

cmd_audit() {
    echo -e "${BOLD}Installation History${NC}"
    echo "────────────────────────────────"

    if [ ! -f "$META_FILE" ]; then
        echo "No installation history found."
        exit 0
    fi

    python3 - <<PYEOF
import json
data = json.load(open('$META_FILE'))
history = data.get('history', [])
if not history:
    print("No history.")
else:
    for i, entry in enumerate(reversed(history), 1):
        marker = "→ current" if i == 1 else ""
        print(f"  [{len(history)-i+1}] {entry.get('installed_at','?')[:19]}  "
              f"role={entry.get('role','?')}  "
              f"version={entry.get('version','?')}  "
              f"by={entry.get('installed_by','?')}  {marker}")
PYEOF
}

cmd_roles() {
    echo -e "${BOLD}Available Roles${NC}"
    echo "────────────────────────────────"
    for role in $VALID_ROLES; do
        local role_file="$CONFIGS_DIR/${role}.md"
        local version="(file not found)"
        if [ -f "$role_file" ]; then
            version=$(version_of "$role_file")
        fi
        printf "  %-12s %s\n" "$role" "v$version"
    done
    echo ""
    echo "Install: ./manage.sh install --role <role>"
}

# ── Main ─────────────────────────────────────────────────────────────────────

if [ $# -eq 0 ]; then
    echo "Usage: ./manage.sh <command> [options]"
    echo ""
    echo "Commands:"
    echo "  install --role <role>   Install role-specific CLAUDE.md"
    echo "  list                    Show current configuration"
    echo "  verify                  Check if CLAUDE.md is unmodified"
    echo "  audit                   Show installation history"
    echo "  roles                   List available roles"
    echo ""
    echo "Options for install:"
    echo "  --dry-run               Preview without writing"
    echo "  --force                 Reinstall even if up to date"
    exit 0
fi

case "$1" in
    install) shift; cmd_install "$@" ;;
    list)    cmd_list ;;
    verify)  cmd_verify ;;
    audit)   cmd_audit ;;
    roles)   cmd_roles ;;
    *)
        echo -e "${RED}Unknown command: $1${NC}"
        echo "Run './manage.sh' for usage."
        exit 1
        ;;
esac
